In [37]:
# ICP - 3, DHiraj Bandi, 700760856
#Question a
import numpy as np

'''firstly I am going to Create a random vector of size 15 with integers in the range 1 to 20
with the numpy random function'''
random_vector = np.random.randint(1, 21, size=15)
print("Random vector:", random_vector)

'''Now I am going to reshape the array to 3 by 5'''
reshaped_array = random_vector.reshape(3, 5)
print("Reshaped array:\n", reshaped_array)

'''Then I am going to print the shape of the array'''
print("Array shape:", reshaped_array.shape)

'''Now I am going to replace the maximum value in each row with 0'''
for i in range(reshaped_array.shape[0]):
    max_index = np.argmax(reshaped_array[i])
    reshaped_array[i, max_index] = 0

print("Modified array:\n", reshaped_array)


Random vector: [19  3 20 10  3 19 10 15  6 20  4  8  7 19  5]
Reshaped array:
 [[19  3 20 10  3]
 [19 10 15  6 20]
 [ 4  8  7 19  5]]
Array shape: (3, 5)
Modified array:
 [[19  3  0 10  3]
 [19 10 15  6  0]
 [ 4  8  7  0  5]]


In [39]:
import numpy as np
''' Now in this question we were given to Create a 2-dimensional array of size 4x3
 with 4-byte integer elements'''
array = np.random.randint(1, 100, size=(4, 3), dtype=np.int32)

'''now I am going to print the shape of the array'''
print("Array shape:", array.shape)

'''now I am going to print the type of the array'''
print("Array type:", type(array))

'''lastly I am going to print the data type of the array'''
print("Array data type:", array.dtype)


Array shape: (4, 3)
Array type: <class 'numpy.ndarray'>
Array data type: int32


In [38]:
import numpy as np

#Question b
''' firstly I am going to Create the given array'''
matrix = np.array([[3, -2], [1, 0]])

''' then I am going to compute the eigenvalues and right eigenvectors of the matrix
using the numpy.linalg.eig function'''
eigenvalues, eigenvectors = np.linalg.eig(matrix)

'''lastly Im just going to print them both '''
print("Eigenvalues:", eigenvalues)
print("Right eigenvectors:\n", eigenvectors)


Eigenvalues: [2. 1.]
Right eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [40]:
#Question c
import numpy as np

'''firstly creating the given array'''
array = np.array([[0, 1, 2], [3, 4, 5]])

'''now I am going to extract the diagonal elements of the array'''
diagonal_elements = np.diag(array)

'''lastly I am going to compute the sum of the diagonal elements'''
sum_of_diagonal = np.sum(diagonal_elements)

'''then I am going to print them both'''
print("Diagonal elements:", diagonal_elements)
print("Sum of diagonal elements:", sum_of_diagonal)


Diagonal elements: [0 4]
Sum of diagonal elements: 4


In [41]:
#Question d
import numpy as np

'''firstly I am going to Create the given array'''
original_array = np.array([[1, 2], [3, 4], [5, 6]])

'''now lets see the original array'''
print("Original array (3x2):")
print(original_array)

'''then I am going to reshape the array to 2x3'''
reshaped_array = original_array.reshape(2, 3)

'''lastly I am going to print the reshaped array'''
print("\nReshaped array (2x3):")
print(reshaped_array)


Original array (3x2):
[[1 2]
 [3 4]
 [5 6]]

Reshaped array (2x3):
[[1 2 3]
 [4 5 6]]
